modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${github}/issues"

[[mods]]
    modId="visceralib_configs"
    version="${version}"
    displayName="VisceraLib-Configs"
    authors="${authors}"
    credits="${contributors}"
    description="Contains code to help with building configs."
    logoFile="assets/visceralib_configs/logo.png"
    logoBlur=false
    displayURL="${github}"

[[mixins]]
    config="mixins/visceralib_configs-common.mixins.json"
[[mixins]]
    config="mixins/visceralib_configs-neoforge.mixins.json"
[[mixins]]
    config="mixins/visceralib_configs-common.client.mixins.json"
[[mixins]]
    config="mixins/visceralib_configs-neoforge.client.mixins.json"
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.visceralib_configs]]
    modId="neoforge"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.visceralib_configs]]
    modId="minecraft"
    type="required"
    versionRange="[${minMinecraft},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.visceralib_configs]]
    modId="visceralib_core"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[modproperties.modmenu]
    badges=[ "library" ]
[modproperties.modmenu_parent]
    id="visceralib"
    name="VisceraLib"
    description="${description}"
    icon="assets/visceralib_configs/logo.png"
    badges= [ "library" ]