modLoader="javafml"
loaderVersion="*"
license="${license}"

[[mods]]
modId="${id}"
displayName="${name}"
description="${description}"
authors="${authors}"
version="${version}"
logoFile="icon.png"
logoBlur=false

[[mixins]]
config = "visceralib-common.mixins.json"

[[mixins]]
config = "visceralib-forge.mixins.json"
