modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${github}/issues"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="${authors}"
description="${description}"
logoFile="icon.png"
logoBlur=false
displayURL=""

[[mixins]]
config="${id}-common.mixins.json"

[[mixins]]
config="${id}-forge.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${id}]]
modId="forge"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
mandatory=true
versionRange="[${minMinecraft},)"
ordering="NONE"
side="BOTH"