modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${github}/issues"

[[mods]]
    modId="visceralib_registration"
    version="${version}"
    displayName="VisceraLib-Registration"
    authors="${authors}"
    credits="${contributors}"
    description="Contains code to help with registering content in common."
    logoFile="assets/visceralib_registration/logo.png"
    logoBlur=false
    displayURL="${github}"

[[mixins]]
    config="mixins/visceralib_registration-common.mixins.json"
[[mixins]]
    config="mixins/visceralib_registration-neoforge.mixins.json"
[[mixins]]
    config="mixins/visceralib_registration-common.client.mixins.json"
[[mixins]]
    config="mixins/visceralib_registration-neoforge.client.mixins.json"
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.visceralib_registration]]
    modId="neoforge"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.visceralib_registration]]
    modId="minecraft"
    type="required"
    versionRange="[${minMinecraft},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.visceralib_registration]]
    modId="visceralib_core"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[modproperties.modmenu]
    badges=[ "library" ]
[modproperties.modmenu_parent]
    id="visceralib"
    name="VisceraLib"
    description="${description}"
    icon="assets/visceralib_registration/logo.png"
    badges=["library"]