modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${github}/issues"

[[mods]]
modId="${id}_${module}"
version="${version}"
displayName="${name}-${moduleCaps}"
authors="${authors}"
description="Contains code to help with loading different model formats."
logoFile="logo.png"
logoBlur=false
displayURL=""

[[mixins]]
config="${id}_${module}-common.mixins.json"

[[mixins]]
config="${id}_${module}-neoforge.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${id}_${module}]]
modId="neoforge"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.${id}_${module}]]
modId="visceralib_core"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.${id}_${module}]]
modId="minecraft"
type="required"
versionRange="[${minMinecraft},)"
ordering="NONE"
side="BOTH"

[modproperties.modmenu]
badges=["library"]

[modproperties.modmenu_parent]
id="${id}"
name= "${name}"
description= "${description}"
icon= "logo.png"
badges= ["library"]