modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${github}/issues"

[[mods]]
modId="visceralib_modelloader"
version="${version}"
displayName="VisceraLib-ModelLoader"
authors="${authors}"
description="${description}"
logoFile="icon.png"
logoBlur=false
displayURL=""

[[mixins]]
config="visceralib_modelloader-common.mixins.json"

[[mixins]]
config="visceralib_modelloader-neoforge.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.visceralib_modelloader]]
modId="neoforge"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.visceralib_modelloader]]
modId="minecraft"
type="required"
versionRange="[${minMinecraft},)"
ordering="NONE"
side="BOTH"